### ISSUE TITLE
edit_url link is not correct for all the pages generated from markdown files and named like ../index.md

### ISSUE THREAD

**Issue by sergkoudi** [adaltas/node-nikita-docs#3]
The link is incorrect for index pages.
For example here:
https://nikita.js.org/about/

it opens this page for editing:
https://github.com/adaltas/node-nikita-docs/edit/master/src/md/about.md

But the right link is:
https://github.com/adaltas/node-nikita-docs/edit/master/src/md/about/index.md

This happens because of the method `createFilePath` of the plugin `gatsby-source-filesystem` removes the name  like `index`.

Here `../node_modules/gatsby-source-filesystem/create-file-path.js`:
```
const parsedName = name === `index` ? `` : name;
return path.posix.join(`/`, dir, parsedName, trailingSlash ? `/` : ``);
```

**Comment by wdavidw** [comment]
Good catch

**Comment by sergkoudi** [comment]
I think it should be optional in the method `createFilePath` and we could suggest to add a new boolean parameter to this function.

It has these input parameters:
```javascript
createFilePath({
  // The node you'd like to convert to a path
  // e.g. from a markdown, JSON, YAML file, etc
  node:
  // Method used to get a node
  // The parameter from `onCreateNode` should be passed in here
  getNode:
  // The base path for your files.
  // Defaults to `src/pages`. For the example above, you'd use `src/content`.
  basePath:
  // Whether you want your file paths to contain a trailing `/` slash
  // Defaults to true
  trailingSlash:
})
```

How do you think @wdavidw ?

**Comment by wdavidw** [comment]
I hesitate, we don't really need to use `createFilePath` at all.

**Comment by sergkoudi** [comment]
What is instead it?

**Comment by sergkoudi** [comment]
I did like this:
```javascript
    edit_url = ''
    if (node.fileAbsolutePath) {
      edit_url =
        "https://github.com/adaltas/node-parameters-docs/edit/master" +
        node.fileAbsolutePath.replace(__dirname, '')
    }
    createNodeField({
      node,
      name: `edit_url`,
      value: edit_url,
    })
```

**Comment by wdavidw** [comment]
[Oh!!](https://nodejs.org/api/path.html#path_path_relative_from_to). And the condition is not necessary, `node.fileAbsolutePath` is always here.
